### ISSUE TITLE
为什么没有崩溃log呢

### ISSUE THREAD

**Issue by 595650661** [lsmakethebest/LSSafeProtector#1]
![default](https://user-images.githubusercontent.com/15205536/44023801-04ef9b00-9f1e-11e8-8970-346af259e33f.png)

**Comment by lsmakethebest** [comment]
open开启的时候，方法传入的参数为NO，代表不是debug模式，你改成YES就好了，我忘给改回去了😓

**Comment by lsmakethebest** [comment]
你可以看下最新代码，更新了部分东西

**Comment by 595650661** [comment]
![2](https://user-images.githubusercontent.com/15205536/44024746-cacd24c6-9f20-11e8-978c-a439610ff02c.png)
您好，在swift中使用貌似没有crash log，可能是我用的问题？

**Comment by lsmakethebest** [comment]
这个在swift里好像不太好用，我刚才swift试了一下，崩溃没防止住，直接闪退了

**Comment by 595650661** [comment]
嗯 期待支持一下swift，可以提高开发效率的工具

**Comment by lsmakethebest** [comment]
已关闭
