### ISSUE TITLE
每次启动xcode断点都会崩溃在try内部，点击跳过又就跳过去了

### ISSUE THREAD

**Issue by LiZhiDaDa** [lsmakethebest/LSSafeProtector#11]
![image](https://user-images.githubusercontent.com/17950054/53948379-a7a72580-4102-11e9-8d6b-aa679b5f75ce.png)

**Comment by LiZhiDaDa** [comment]
就是崩溃在这个try内部这句话。我想跳过这个异常，但是不知道怎么跳，网上的解决办法还要写脚本，懒得写。

**Comment by lsmakethebest** [comment]
这不是崩溃，这是断点

**Comment by LiZhiDaDa** [comment]
对不起，表达错误，是个断点，但是别的地方没有设置断点，只是打了个全局断点就会卡在这里，每次装app都跳这里不方便，不打全局断点又不现实，所以我想跳过这个异常，但是没找到方法，所以我是这么处理的，只在release模式启动。
![image](https://user-images.githubusercontent.com/17950054/54862361-a4ec3780-4d74-11e9-8316-027f827e350f.png)

**Comment by tipshot** [comment]
之前我遇到过，只要存在全局断点，每次运行都会断在appDelegate或者TabBarVC的某个地方，或者是其他的基础框架的某个地方，很奇怪，不知道原因，如果你找到原因了，麻烦告诉俺一下。 @LiZhiDaDa

**Comment by LiZhiDaDa** [comment]
@tipshot   哈哈哈哈，找到了肯定告诉你

**Comment by tipshot** [comment]
@LiZhiDaDa 我找到了也告诉你。哈哈

**Comment by tipshot** [comment]
@LiZhiDaDa 找到了么？

**Comment by LiZhiDaDa** [comment]
@tipshot 并没有找到，我的解决方案 还是只在release的时候才开启监听

**Comment by lsmakethebest** [comment]
你开异常断点了吗，不开异常断点应该不会断住




在2019年07月30日 10:41，Thread_Fight_Queue 写道：

@tipshot 并没有找到，我的解决方案 还是只在release的时候才开启监听

**Comment by LiZhiDaDa** [comment]
> 你开异常断点了吗，不开异常断点应该不会断住 在2019年07月30日 10:41，Thread_Fight_Queue 写道： @tipshot 并没有找到，我的解决方案 还是只在release的时候才开启监听 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or mute the thread.

在debug模式开了一个全局断点

**Comment by lsmakethebest** [comment]
去掉应该就好了




在2019年07月30日 16:57，Thread_Fight_Queue 写道：

你开异常断点了吗，不开异常断点应该不会断住 在2019年07月30日 10:41，Thread_Fight_Queue 写道： @tipshot 并没有找到，我的解决方案 还是只在release的时候才开启监听 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or mute the thread.

在debug模式开了一个全局断点
