### ISSUE TITLE
-(void)safe_KVODealloc  遇到AAChartKit 的 AAChartView时候，会不停息的调用，请问怎么回事？

### ISSUE THREAD

**Issue by tipshot** [lsmakethebest/LSSafeProtector#12]
<img width="1340" alt="WX20190328-165846@2x" src="https://user-images.githubusercontent.com/18547353/55144523-f7b25e80-517b-11e9-84f0-6756278eaf2b.png">

**Comment by lsmakethebest** [comment]
内部控件销毁就会走这个逻辑
