### ISSUE TITLE
上传了正确的符号表之后，出错堆栈无法还原定位信息

### ISSUE THREAD

**Issue by LiZhiDaDa** [lsmakethebest/LSSafeProtector#14]
上传正确的符号表文件，bugly自己捕获的崩溃，在“崩溃分析”一栏能定位到崩溃方法，但是通过LSSafeProtector捕捉到的崩溃上传bugly之后只显示堆栈信息，定位不到对应的方法
![image](https://user-images.githubusercontent.com/17950054/56717258-d3dc3b80-676e-11e9-8edd-cd15564f8b42.png)

**Comment by LiZhiDaDa** [comment]
下图是LSSafeProtector捕捉到崩溃之后，上传到bugly产生的log文件
![image](https://user-images.githubusercontent.com/17950054/56717495-56fd9180-676f-11e9-88a8-4443d0bc67d1.png)

**Comment by lsmakethebest** [comment]
有的确实是定位不到，这个跟框架本身没关系




在2019年04月25日 15:31，Thread_Fight_Queue 写道：

上传正确的符号表文件，bugly自己捕获的崩溃，在“崩溃分析”一栏能定位到崩溃方法，但是通过LSSafeProtector捕捉到的崩溃上传bugly之后只显示堆栈信息，定位不到对应的方法

**Comment by lyc59621** [comment]
NSString * extraInfo= [self attachmentForException:exception];
        extraInfo = extraInfo?extraInfo:@"非debug,不上传log";
        NSDictionary *userInfo = exception.userInfo;
        NSString *symbolsString = userInfo[@"callStackSymbols"];
        NSArray *symbolsArray = [symbolsString componentsSeparatedByString:@"\n"];
         [Bugly reportExceptionWithCategory:3 name:exception.name reason:[NSString stringWithFormat:@"崩溃位置:%@",exception.reason,exception.userInfo[@"location"]] callStack:symbolsArray extraInfo:@{@"log":extraInfo,@"userInfo":userInfo} terminateApp:NO];



建议试试改成这个方法
