### ISSUE TITLE
崩溃了。

### ISSUE THREAD

**Issue by hkjin** [lsmakethebest/LSSafeProtector#17]
![image](https://user-images.githubusercontent.com/17734586/60805998-66a84600-a1b4-11e9-8bc6-74555b578c1d.png)

**Comment by hkjin** [comment]
bugly收集到的

**Comment by lsmakethebest** [comment]
帮忙看一下崩溃设备信息，以及数量，以及使用的LSSafePrrotector版本号，如果可以的话，加个qq沟通下把 623501561




在2019年07月08日 19:13，Kegem 写道：

bugly收集到的
