### ISSUE TITLE
使用AVPlayer播放的时候Crash 掉了

### ISSUE THREAD

**Issue by Loveying** [lsmakethebest/LSSafeProtector#2]
Cannot remove an observer <AVKVODispatcher 0x600000018f60> for the key path "currentItem" from <AVPlayer 0x600000018650> because it is not registered as an observer.
		[Crash Location]: -[NSObject(KVOSafe) safe_removeObserver:forKeyPath:]

**Comment by lsmakethebest** [comment]
不知道你是什么时候下载的代码，最好更新下最新代码，如果还是crash，希望能提供步骤，我去排查一下

**Comment by lsmakethebest** [comment]
可以加我qq:623501561 方便沟通

**Comment by lsmakethebest** [comment]
已解决

**Comment by anfernees-iphone** [comment]
demo点击直接就闪退了

**Comment by lsmakethebest** [comment]
因为isDebug参数为YES，测试环境就是要让他闪退的，这样才能发现bug及时修改，控制台已经将捕获到的信息打印出来了，闪退是我用断言故意闪退的，你可以将参数设置为NO代表线上，不打印，不断言闪退




在2018年08月16日 19:47，anfernees-iphone 写道：

demo点击直接就闪退了
