### ISSUE TITLE
新版怎么不兼容iOS10的了？

### ISSUE THREAD

**Issue by jianjianhao** [lsmakethebest/LSSafeProtector#5]
<img width="1112" alt="2018-09-18 10 28 52" src="https://user-images.githubusercontent.com/12797357/45660906-ad498880-bb2d-11e8-80ed-d4a3215ba883.png">
我记得上次iOS10是没问题的吧，更新之后测试了下结果出问题了

**Comment by lsmakethebest** [comment]
因为ios11以下，交换那个方法会导致显示键盘的地方此时退到后台会闪退，所以去掉那个方法交换了，如果非要做方法交换也是可以，那就得用mrc方法,对那个文件进行强制mrc,-fno-objc-arc,然后里面用mrc写法

**Comment by jianjianhao** [comment]
好吧，我看了其他的两个，可以参考一下吧
https://github.com/jasenhuang/NSObjectSafe
https://github.com/JJMM/SafeKit

**Comment by lsmakethebest** [comment]
我是不想用户集成到项目的时候太麻烦，不想让用户还得手动添加-fno-objc-arc，也考虑到ios10以下用户不是很多，所以没有那样做

**Comment by jianjianhao** [comment]
ok

**Comment by lsmakethebest** [comment]
老铁应你的要求以及修改 ,可以直接下载代码得手动设置-fno-objc-arc，pod还得稍等，如果是pod导入不用设置-fno-objc-arc
