### ISSUE TITLE
老是在这一行崩   搞得一头雾水

### ISSUE THREAD

**Issue by chglog** [lsmakethebest/LSSafeProtector#8]
-(NSRecursiveLock *)safe_lock
{
    @synchronized(self){
        LSRecursiveLock *myLock=objc_getAssociatedObject(self, _cmd);
        if (myLock==nil) {
            myLock=[[LSRecursiveLock alloc]init];
            self.safe_lock=myLock;
        }
        return myLock;
    }
}

**Comment by lsmakethebest** [comment]
还是截图发我看看吧， 我们还是加qq吧，623501561 方便沟通




在2018年12月25日 14:32，chglog 写道：

-(NSRecursiveLock *)safe_lock
{
@synchronized(self){
LSRecursiveLock *myLock=objc_getAssociatedObject(self, _cmd);
if (myLock==nil) {
myLock=[[LSRecursiveLock alloc]init];
self.safe_lock=myLock;
}
return myLock;
}
}
