### ISSUE TITLE
使用该库上架App Store, 是否会因为非公共APIS被拒!?

### ISSUE THREAD

**Issue by faith939339094** [lsmakethebest/LSSafeProtector#9]

**Comment by lsmakethebest** [comment]
不会，这里没有使用私有api




在2019年01月19日 11:32，faith939339094 写道：

**Comment by RtzX** [comment]
我看其他相关的 safe 的时候.看到有人评论说  `objc_getClass` 是私有api  他们的App 被拒了 ... 不知道 真假.. 其实对我来说 没影响的... 我是企业证书 ...  就是想求证一下 .

**Comment by lsmakethebest** [comment]
不会影响上架，这个问题之前有人问过，也做过验证不会影响上架，我自己公司的app也没问题，也都正常上架




在2019年03月17日 15:28，Lyle 写道：

我看其他相关的 safe 的时候.看到有人评论说 objc_getClass 是私有api 他们的App 被拒了 ... 不知道 真假.. 其实对我来说 没影响的... 我是企业证书 ... 就是想求证一下 .

**Comment by RtzX** [comment]
如果能提供一个 简易的 `API` 就好了 比如: 开启这个功能
 
   

      - (void)start
       {
           #ifdef DEBUG
               [LSSafeProtector openSafeProtectorWithIsDebug:YES block:nil];
          #else
               [LSSafeProtector openSafeProtectorWithIsDebug:NO block:nil];
         #endif
       }
